name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # v2.0.0
      - uses: haskell/actions/setup@f7b0997283589ea5a6b4f2ade6a239d70a412877
        id: setup-haskell

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: ${{ hashFiles('cabal.project.freeze') }}

      - name: Build deps & executable
        run: cabal build
      
      - name: Generate website
        run: cabal run benjamin-pizza build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: _site

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
