name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # v2.7.5
      - uses: haskell-actions/setup@ec49483bfc012387b227434aba94f59a6ecd0900
        id: setup-haskell
        with:
          ghc-version: 9.4
          cabal-version: 3.10

      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: benjamin-pizza

      - name: Build deps & executable
        run: cabal build

      - name: Generate website
        run: cabal run benjamin-pizza build

      - name: Deploy
        # v4.6.3
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2
        with:
          branch: gh-pages
          folder: _site

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
