name: Build

on:
  push:
    branches: [ live ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: cache

      - name: Install dependencies
        run: stack --no-terminal --install-ghc build --ghc-options -O2 --only-dependencies

      - name: Build executable
        run: stack --no-terminal build --ghc-options -O2 --copy-bins --local-bin-path ./bin
      
      - name: Generate website
        run: stack exec benjamin-pizza build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: _site

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
