name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # v2.0.2
      - uses: haskell/actions/setup@97d6391f4afce6357da121cd189e6a1cce8d13ec
        id: setup-haskell
        with:
          ghc-version: 9.2
          cabal-version: 3.6

      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: benjamin-pizza

      - name: Build deps & executable
        run: cabal build

      - name: Generate website
        run: cabal run benjamin-pizza build

      - name: Deploy
        # v4.4.1
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          branch: gh-pages
          folder: _site

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site
