name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # v2.7.5
      - uses: haskell-actions/setup@ec49483bfc012387b227434aba94f59a6ecd0900
        id: setup
        with:
          ghc-version: '9.4'
          cabal-version: '3.10'

      - name: Create build plan
        run: |
          cabal build all --dry-run

      - uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies

      - uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Generate website
        run: cabal run benjamin-pizza build

      - name: Deploy
        # v4.6.3
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2
        with:
          branch: gh-pages
          folder: _site

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
