name: Update freeze file

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update_freeze_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # v2.0.0
      - uses: haskell/actions/setup@f7b0997283589ea5a6b4f2ade6a239d70a412877
        id: setup-haskell

      - name: Regenerate freeze file
        run: rm -f cabal.project.freeze && cabal freeze

      # v4.0.4
      - uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          title: Update cabal freeze file
          commit-message: Update cabal freeze file
