name: Update freeze file

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update_freeze_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: cabal freeze

      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update cabal freeze file
